baseURL = "https://www.mathiasdejong.be/"
languageCode = "en-us"
title = "Mathias de Jong"
theme = "mathiasdejongbe"

[params]
    logo = "img/avatar.jpg"
    default_spoiler_summary = "Click to expand..."

[menu]
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 1
    [[menu.main]]
        name = "Tags"
        url = "/tags/"
        weight = 2

[taxonomies]
    tag = "tags"

[markup]
    [markup.highlight]
        style = "nord"
        noClasses = false

[markup.goldmark.renderer]
unsafe = true
